FROM node:18.15.0-alpine AS development

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install glob rimraf

RUN npm install --only=development

COPY . .


CMD npx -y prisma generate ; npm run start:dev
